# Generated by Django 2.1 on 2018-08-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseParking', '0002_auto_20180825_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=15)),
                ('amount', models.IntegerField(max_length=5)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseParking.Post')),
            ],
        ),
    ]
