# Generated by Django 2.1 on 2018-08-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseParking', '0003_datepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepost',
            name='number',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='DatabaseParking.Post'),
        ),
    ]
