# Generated by Django 2.1 on 2018-08-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseParking', '0004_auto_20180825_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datepost',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
